export const STORAGE_KEY_NOTIFICACOES = 'cvholding_notificacoes'
export const STORAGE_KEY_TAREFAS = 'cvholding_tarefas_manuais'

export const STATUS_NOTIFICACAO = {
  NAO_LIDA: 'NAO_LIDA',
  LIDA: 'LIDA',
  RESOLVIDA: 'RESOLVIDA',
  ARQUIVADA: 'ARQUIVADA',
}

export const STATUS_TAREFA = {
  PENDENTE: 'PENDENTE',
  CONCLUIDA: 'CONCLUIDA',
}

export const PRIORIDADE_NOTIFICACAO = {
  CRITICA: 'CRITICA',
  ALTA: 'ALTA',
  MEDIA: 'MEDIA',
  BAIXA: 'BAIXA',
}

export const TIPOS_NOTIFICACAO = {
  ALUGUEL_VENCIDO: 'ALUGUEL_VENCIDO',
  CONTA_VENCIDA: 'CONTA_VENCIDA',
  CONTA_VENCENDO_7_DIAS: 'CONTA_VENCENDO_7_DIAS',
  CONTRATO_VENCENDO_30_DIAS: 'CONTRATO_VENCENDO_30_DIAS',
  CONTRATO_VENCENDO_60_DIAS: 'CONTRATO_VENCENDO_60_DIAS',
  CONTRATO_VENCENDO_90_DIAS: 'CONTRATO_VENCENDO_90_DIAS',
  REAJUSTE_PENDENTE: 'REAJUSTE_PENDENTE',
  DOCUMENTO_VENCENDO: 'DOCUMENTO_VENCENDO',
  UNIDADE_VAGA: 'UNIDADE_VAGA',
  SALDO_NEGATIVO_CONTA: 'SALDO_NEGATIVO_CONTA',
  TAREFA_MANUAL: 'TAREFA_MANUAL',
}

export const MODULOS_NOTIFICACAO = [
  'Financeiro',
  'Contratos',
  'Documentos',
  'Unidades',
  'Notificacoes',
]

export const EVENTO_ATUALIZACAO_NOTIFICACOES = 'cvholding_notificacoes_updated'
