export const STORAGE_KEY_CONFIGURACOES = 'cvholding_configuracoes'
export const EVENTO_CONFIGURACOES_ATUALIZADAS = 'cvholding_configuracoes_updated'

export const SECOES_CONFIGURACOES = [
  'holding',
  'financeiro',
  'contratos',
  'documentos',
  'notificacoes',
  'interface',
]

export const TIPOS_PARAMETROS_NOTIFICACAO = {
  ALUGUEL_VENCIDO: 'ALUGUEL_VENCIDO',
  CONTA_VENCIDA: 'CONTA_VENCIDA',
  CONTA_VENCENDO_7_DIAS: 'CONTA_VENCENDO_7_DIAS',
  CONTRATO_VENCENDO_30_DIAS: 'CONTRATO_VENCENDO_30_DIAS',
  CONTRATO_VENCENDO_60_DIAS: 'CONTRATO_VENCENDO_60_DIAS',
  CONTRATO_VENCENDO_90_DIAS: 'CONTRATO_VENCENDO_90_DIAS',
  REAJUSTE_PENDENTE: 'REAJUSTE_PENDENTE',
  DOCUMENTO_VENCENDO: 'DOCUMENTO_VENCENDO',
  UNIDADE_VAGA: 'UNIDADE_VAGA',
  SALDO_NEGATIVO_CONTA: 'SALDO_NEGATIVO_CONTA',
}
